import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "../components/Sidebar";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Next Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-blue-950">
        <div className="flex min-h-screen bg-[#030014f2]">
          {/* Sidebar */}
          <Sidebar className="w-64 min-h-screen bg-none fixed left-0 top-0" />

          {/* Main content area */}
          <div className="flex flex-col flex-1">
            {/* Header */}
            <Header className="w-full text-white h-16 shadow-md sticky top-0 bg-none z-10" />

            {/* Content */}
            <main className="flex-1 p-6 mt-0">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}