import type { Metadata } from "next";
import "./globals.css";
import DashboardLayoutClient from "@/components/DashboardLayoutClient";

export const metadata: Metadata = {
  title: "Next Dashboard",
  description: "Generated by create next app",
  icons: "/arlogo.png",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-blue-950">
        <DashboardLayoutClient>
          {children}
        </DashboardLayoutClient>
      </body>
    </html>
  );
}